name: Create & Push Business Central NuGet Packages
description: Build each .app once and push it to every matching NuGet feed
branding:
  icon:  'package'
  color: 'orange'
inputs:
  feed-map:
    description: Path to the feed-map JSON file (GUID -> {url, token-secret})
    required: false
    default: ./nuget-feed-map.json
  fail-on-any-error:
    description: |
      true  -> the step fails if **any** push fails  
      false -> the job succeeds even with partial uploads (see summary)
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Upload Business Central .app files
      shell: pwsh
      env:
        ACTION_PATH: ${{ github.action_path }}
        FEED_MAP_PATH: ${{ inputs.feed-map }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}   # default feed auth
        FAIL_ON_ANY_ERROR: ${{ inputs.fail-on-any-error }}
      run: |
        $scriptPath = Join-Path $env:ACTION_PATH 'scripts/Publish-AppPackages.ps1'
        & $scriptPath
