name: Upload BC .app Files to NuGet
description: Process and push .app files in ./upload to NuGet

inputs:
  feed-map:
    description: Path to the feed map JSON file
    required: false
    default: ./nuget-feed-map.json

runs:
  using: "composite"
  steps:
    - name: Upload Business Central .app files to NuGet
      shell: pwsh
      env:
        ACTION_PATH: ${{ github.action_path }}
        FEED_MAP_PATH: ${{ inputs.feed-map }}
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      run: |
        $scriptPath = Join-Path "$env:ACTION_PATH" "scripts/Publish-AppPackages.ps1"
        if (-not (Test-Path $scriptPath)) {
            Write-Error "Upload script not found at $scriptPath"
            exit 1
        }
        Write-Host "Executing Publish-AppPackages.ps1 from $scriptPath"
        & $scriptPath
